"""
Report generation for log analysis results.

Exports analysis results to Markdown and HTML formats for
sharing and documentation purposes.
"""

from datetime import datetime
from pathlib import Path
from typing import Optional

from .analyzer import AnalysisResult


class ReportGenerator:
    """Generate reports from analysis results."""
    
    def __init__(self, result: AnalysisResult):
        """
        Initialize the report generator.
        
        Args:
            result: AnalysisResult to generate report from
        """
        self.result = result
    
    def to_markdown(self) -> str:
        """
        Generate a Markdown report.
        
        Returns:
            Markdown-formatted report string
        """
        r = self.result
        lines = []
        
        # Header
        lines.append(f"# Log Analysis Report")
        lines.append("")
        lines.append(f"**File:** `{Path(r.filepath).name}`  ")
        lines.append(f"**Format:** {r.detected_format}  ")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        
        # Overview
        lines.append("## Overview")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Total Lines | {r.total_lines:,} |")
        lines.append(f"| Parsed Lines | {r.parsed_lines:,} |")
        lines.append(f"| Failed Lines | {r.failed_lines:,} |")
        lines.append(f"| Parse Success Rate | {r.parse_success_rate:.1f}% |")
        lines.append(f"| Error Rate | {r.error_rate:.1f}% |")
        
        if r.earliest_timestamp:
            lines.append(f"| First Entry | {r.earliest_timestamp.strftime('%Y-%m-%d %H:%M:%S')} |")
        if r.latest_timestamp:
            lines.append(f"| Last Entry | {r.latest_timestamp.strftime('%Y-%m-%d %H:%M:%S')} |")
        if r.time_span:
            lines.append(f"| Time Span | {r.time_span} |")
        lines.append("")
        
        # Severity breakdown
        if r.level_counts:
            lines.append("## Severity Breakdown")
            lines.append("")
            lines.append("| Level | Count | Percentage |")
            lines.append("|-------|-------|------------|")
            for level in ['CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG']:
                count = r.level_counts.get(level, 0)
                if count > 0:
                    pct = (count / r.parsed_lines * 100) if r.parsed_lines > 0 else 0
                    emoji = {'CRITICAL': '🔴', 'ERROR': '🟠', 'WARNING': '🟡', 
                            'INFO': '🟢', 'DEBUG': '⚪'}
                    lines.append(f"| {emoji.get(level, '')} {level} | {count:,} | {pct:.1f}% |")
            lines.append("")
        
        # HTTP Status Codes
        if r.status_codes:
            lines.append("## HTTP Status Codes")
            lines.append("")
            lines.append("| Code | Count | Category |")
            lines.append("|------|-------|----------|")
            categories = {
                2: "✅ Success",
                3: "↪️ Redirect", 
                4: "⚠️ Client Error",
                5: "❌ Server Error"
            }
            for code in sorted(r.status_codes.keys()):
                count = r.status_codes[code]
                cat = categories.get(code // 100, "Unknown")
                lines.append(f"| {code} | {count:,} | {cat} |")
            lines.append("")
        
        # Top Errors
        if r.top_errors:
            lines.append("## Top Error Messages")
            lines.append("")
            lines.append("| Count | Message |")
            lines.append("|-------|---------|")
            for msg, count in r.top_errors[:10]:
                # Escape pipe characters and truncate
                safe_msg = msg.replace("|", "\\|")[:80]
                lines.append(f"| {count} | {safe_msg} |")
            lines.append("")
        
        # Top Sources
        if r.top_sources:
            lines.append("## Top Sources")
            lines.append("")
            lines.append("| Source | Requests |")
            lines.append("|--------|----------|")
            for source, count in r.top_sources[:10]:
                lines.append(f"| {source} | {count:,} |")
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("*Generated by Log Analyzer Toolkit*")
        
        return "\n".join(lines)
    
    def to_html(self) -> str:
        """
        Generate an HTML report.
        
        Returns:
            HTML-formatted report string
        """
        r = self.result
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log Analysis Report - {Path(r.filepath).name}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .report {{
            background: white;
            border-radius: 8px;
            padding: 30px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{ background: #3498db; color: white; }}
        tr:hover {{ background: #f5f5f5; }}
        .stat-card {{
            display: inline-block;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin: 5px;
            min-width: 150px;
            text-align: center;
        }}
        .stat-value {{ font-size: 2em; font-weight: bold; }}
        .stat-label {{ font-size: 0.9em; opacity: 0.9; }}
        .error {{ color: #e74c3c; }}
        .warning {{ color: #f39c12; }}
        .success {{ color: #27ae60; }}
        footer {{ text-align: center; margin-top: 30px; color: #7f8c8d; }}
    </style>
</head>
<body>
    <div class="report">
        <h1>📊 Log Analysis Report</h1>
        <p><strong>File:</strong> <code>{Path(r.filepath).name}</code></p>
        <p><strong>Format:</strong> {r.detected_format}</p>
        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        
        <div style="margin: 20px 0;">
            <div class="stat-card">
                <div class="stat-value">{r.total_lines:,}</div>
                <div class="stat-label">Total Lines</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{r.parse_success_rate:.1f}%</div>
                <div class="stat-label">Parse Rate</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{r.error_rate:.1f}%</div>
                <div class="stat-label">Error Rate</div>
            </div>
        </div>
"""
        
        # Severity breakdown
        if r.level_counts:
            html += """
        <h2>Severity Breakdown</h2>
        <table>
            <tr><th>Level</th><th>Count</th><th>Percentage</th></tr>
"""
            for level in ['CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG']:
                count = r.level_counts.get(level, 0)
                if count > 0:
                    pct = (count / r.parsed_lines * 100) if r.parsed_lines > 0 else 0
                    css_class = {'CRITICAL': 'error', 'ERROR': 'error', 
                                'WARNING': 'warning'}.get(level, '')
                    html += f'            <tr><td class="{css_class}">{level}</td><td>{count:,}</td><td>{pct:.1f}%</td></tr>\n'
            html += "        </table>\n"

        # Top Errors
        if r.top_errors:
            html += """
        <h2>Top Error Messages</h2>
        <table>
            <tr><th>Count</th><th>Message</th></tr>
"""
            for msg, count in r.top_errors[:10]:
                safe_msg = msg[:100].replace('<', '&lt;').replace('>', '&gt;')
                html += f'            <tr><td>{count}</td><td>{safe_msg}</td></tr>\n'
            html += "        </table>\n"
        
        html += """
        <footer>Generated by Log Analyzer Toolkit</footer>
    </div>
</body>
</html>"""
        
        return html
    
    def save(self, output_path: str, format: str = "markdown") -> None:
        """
        Save report to file.
        
        Args:
            output_path: Path to save the report
            format: 'markdown' or 'html'
        """
        if format == "html":
            content = self.to_html()
        else:
            content = self.to_markdown()
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
